CREATE DATABASE IF NOT EXISTS DEALER;
USE DEALER;

CREATE TABLE MANUFACTURERS (
    ID_MF INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE BRANDS (
    ID_BR INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    IS_FLAGSHIP SMALLINT,
    MODEL_COUNT INT NOT NULL,
    ID_MF INT NOT NULL,
    FOREIGN KEY (ID_MF) REFERENCES MANUFACTURERS(ID_MF) ON DELETE CASCADE
);

INSERT INTO MANUFACTURERS (ID_MF, NAME) VALUES (1, 'Volkswagen');
INSERT INTO MANUFACTURERS (ID_MF, NAME) VALUES (2, 'Renault-Nissan-Mitsubishi Alliance');

INSERT INTO BRANDS (ID_BR, NAME, IS_FLAGSHIP, MODEL_COUNT, ID_MF) VALUES (1, 'Volkswagen', TRUE, 50, 1);
INSERT INTO BRANDS (ID_BR, NAME, IS_FLAGSHIP, MODEL_COUNT, ID_MF) VALUES (2, 'Audi', FALSE, 40, 1);
INSERT INTO BRANDS (ID_BR, NAME, IS_FLAGSHIP, MODEL_COUNT, ID_MF) VALUES (3, 'Porsche', FALSE, 30, 1);

INSERT INTO BRANDS (ID_BR, NAME, IS_FLAGSHIP, MODEL_COUNT, ID_MF) VALUES (4, 'Renault', TRUE, 50, 2);
INSERT INTO BRANDS (ID_BR, NAME, IS_FLAGSHIP, MODEL_COUNT, ID_MF) VALUES (5, 'Nissan', TRUE, 40, 2);
INSERT INTO BRANDS (ID_BR, NAME, IS_FLAGSHIP, MODEL_COUNT, ID_MF) VALUES (6, 'Mitsubishi', TRUE, 30, 2);
